### PR TITLE
Changes to README about the "EG THE BEST" edition

### PR DESCRIPTION
**Pull request by Raytwo**
Figured you guys would like to know if this works and it does! Thanks a lot for what you've done, I was hoping someone would work on this.

### CODE REVIEW

**Comment by masagrator** [comment]
Thanks for confirming that. Only change one thing I have pointed out and I will merge it.

**Comment by Raytwo** [comment]
Sorry, what have you pointed out? I see no suggested change.

**Comment by masagrator** [comment]
IMG_20210928_194745

**Comment by Raytwo** [comment]
Strange, I honestly do not see the review. But the requested change has been made. Thanks again!

**Pull request merged**
